### ISSUE TITLE
'no devices found' error

### ISSUE THREAD

**Issue by gliese581gg** [Terabee/python_openni2_samples#1]
Hi.

I followed the Requirements and ran `display_depth_frame.py`.

I got following error : 

```
openni.utils.OpenNIError: (OniStatus.ONI_STATUS_ERROR, b'DeviceOpen using default: no devices found', None)
```

NiViewer in SDK also gives me the same error.

However, I can use `cv2.VideoCapture(0)` to get the frame.

it gives me 60 * 160 * 2 shaped uint8 array, which I could not convert it to 60 * 80 uint16 array.

Is there any way to fix the OpenNI or decode the frame from `cv2.VideoCapture` correctly?

**Comment by 7Horizon** [comment]
Same here, "no devices found"

**Comment by pl-kabaradjian** [comment]
Hello @gliese581gg, @7Horizon,

I invite you to contact support (if not done already) [here](https://www.terabee.com/contact/) so we can better assist you. Please also provide information about your setup such as platform and OS.

Best regards,

**Comment by PHDPeter** [comment]
Did this get solved in the end as I have the same issue?
Using:
Ubuntu 18.04
Single Terabee 3Dcam 80x60

**Comment by JLAsensio** [comment]
It looks like the driver is found in the SDK folder but not outside.
Try to relaunch     install.sh       to force the driver to be installed system-wide. 
 
For faster assistance please contact Terabee using the following link: https://www.terabee.com/contact/
